spring:
  application:
    name: turbine

server:
  port: 8989

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false

turbine:
  app-config: client,config-server
  clusterNameExpression: "'default'"

